### ISSUE TITLE
YouTube Shorts Video Uploading issue on Bluestacks On PC/Windows 11

### ISSUE THREAD

**Issue by Shahnilam78** [etib-corp/r-type#134]
I can try using YouTube app through Bluestacks emulator and try to uploading shorts video but i can facing some error so how can i fix?

**Comment by MAILLOTNathan** [comment]
> I can try using YouTube app through Bluestacks emulator and try to uploading shorts video but i can facing some error so how can i fix?

I think it's not the good project...
